version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    ports:
      - '8000:8000'
    networks:
      - phpsite
    restart: always  
  db:
    image: mysql:5.7
    volumes:
      - db_app:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1
    ports:
      - '3307:3306'
    networks:
      - phpsite
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8889:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1
    networks:
      - phpsite
networks:
  phpsite:
volumes:
  db_app: